export PATH="/home/pratima/Downloads/plumed-test/src/lib/:$PATH"
export LIBRARY_PATH="/home/pratima/Downloads/plumed-test/src/lib/:$LIBRARY_PATH"
export LD_LIBRARY_PATH="/home/pratima/Downloads/plumed-test/src/lib/:$LD_LIBRARY_PATH"
export DYLD_LIBRARY_PATH="/home/pratima/Downloads/plumed-test/src/lib/:$DYLD_LIBRARY_PATH"
export PLUMED_KERNEL="/home/pratima/Downloads/plumed-test/src/lib/libplumedKernel.so"
